// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwI6wDxp4c-0VrBlLHlUQ6CkxiYLRomEk',
    appId: '1:504100298767:web:7ee3a73212034899dc837a',
    messagingSenderId: '504100298767',
    projectId: 'nescafe-app-4a3d0',
    authDomain: 'nescafe-app-4a3d0.firebaseapp.com',
    storageBucket: 'nescafe-app-4a3d0.firebasestorage.app',
    measurementId: 'G-F0VYQB87QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnYTHmpysmPKbcil2av1XuFwXthmygiFA',
    appId: '1:504100298767:android:d50a82938d92d0bedc837a',
    messagingSenderId: '504100298767',
    projectId: 'nescafe-app-4a3d0',
    storageBucket: 'nescafe-app-4a3d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfZwSqvHBSnGrSH_AFD-0PxTxbDpPgPTI',
    appId: '1:504100298767:ios:9339f4559eac8ad7dc837a',
    messagingSenderId: '504100298767',
    projectId: 'nescafe-app-4a3d0',
    storageBucket: 'nescafe-app-4a3d0.firebasestorage.app',
    iosBundleId: 'com.example.nescafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfZwSqvHBSnGrSH_AFD-0PxTxbDpPgPTI',
    appId: '1:504100298767:ios:9339f4559eac8ad7dc837a',
    messagingSenderId: '504100298767',
    projectId: 'nescafe-app-4a3d0',
    storageBucket: 'nescafe-app-4a3d0.firebasestorage.app',
    iosBundleId: 'com.example.nescafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwI6wDxp4c-0VrBlLHlUQ6CkxiYLRomEk',
    appId: '1:504100298767:web:792a29b0676e4654dc837a',
    messagingSenderId: '504100298767',
    projectId: 'nescafe-app-4a3d0',
    authDomain: 'nescafe-app-4a3d0.firebaseapp.com',
    storageBucket: 'nescafe-app-4a3d0.firebasestorage.app',
    measurementId: 'G-6VQ3CS2GM8',
  );
}
